**TASK 1**

1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [0]:
def div(n,d):
  try:
    ans=n/d
  except ZeroDivisionError as z:
    print("Error Dividing by Zero")
    ans='Result is Infinity'
  return ans

In [0]:
div(5,0)

Error Dividing by Zero


'Result is Infinity'

2.Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket

In [0]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
answer=[(sub+" "+vb+" "+obj+".") for sub in subjects for vb in verbs for obj in objects]
for i in answer:
  print(i)


Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


**TASK 2**

In [0]:
import numpy as np

1.Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [0]:
def vanderm(x,N,increasing):
  #if N is not Specified in the Argument or N=None
  if(N==None and increasing==False):
    result1=[[x[i]**(len(x)-j) for j in range(1,len(x)+1)] for i in range(0,len(x))]
    return np.array(result1)
  elif(N==None and increasing==True):
    result2=[[x[i]**(j) for j in range(0,len(x))] for i in range(0,len(x))]
    return np.array(result2)
  #if N is Specified in the Argument
  elif(increasing==False):
    result3=[[x[i]**(N-j) for j in range(1,N+1)] for i in range(0,len(x)) ]
    return np.array(result3)
  else:
    result4=[[x[i]**(j) for j in range(0,N)] for i in range(0,len(x)) ]
    return np.array(result4)

In [35]:
vanderm([1,2,3,4,5,6],None,True)

array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    5,   25,  125,  625, 3125],
       [   1,    6,   36,  216, 1296, 7776]])

In [36]:
vanderm([1,2,3,4,5,6],None,False)

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1],
       [7776, 1296,  216,   36,    6,    1]])

In [37]:
vanderm([1,2,3,4,5,6],3,True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25],
       [ 1,  6, 36]])

In [38]:
vanderm([1,2,3,4,5,6],3,False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1],
       [36,  6,  1]])