In [0]:
import numpy as np

**Problem Statement 1:**Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [0]:
def vanderm(x,N,increasing):
  #if N is not Specified in the Argument or N=None
  if(N==None and increasing==False):
    result1=[[x[i]**(len(x)-j) for j in range(1,len(x)+1)] for i in range(0,len(x))]
    return np.array(result1)
  elif(N==None and increasing==True):
    result2=[[x[i]**(j) for j in range(0,len(x))] for i in range(0,len(x))]
    return np.array(result2)
  #if N is Specified in the Argument
  elif(increasing==False):
    result3=[[x[i]**(N-j) for j in range(1,N+1)] for i in range(0,len(x)) ]
    return np.array(result3)
  else:
    result4=[[x[i]**(j) for j in range(0,N)] for i in range(0,len(x)) ]
    return np.array(result4)

In [5]:
vanderm([1,2,3,4,5,6],None,True)

array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    5,   25,  125,  625, 3125],
       [   1,    6,   36,  216, 1296, 7776]])

In [6]:
vanderm([1,2,3,4,5,6],None,False)

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1],
       [7776, 1296,  216,   36,    6,    1]])

In [7]:
vanderm([1,2,3,4,5,6],3,True)

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25],
       [ 1,  6, 36]])

In [8]:
vanderm([1,2,3,4,5,6],3,False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1],
       [36,  6,  1]])

**Problem Statement 2:**
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown 
below


i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

**Question:** Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [0]:
def movavg(a,w):
  a=np.array(a)
  print('\n Original array : \n',a)
  print('\n Thus, the moving average sequence of above array is : \n')
  for i in range(0,len(a)-w+1):
    ans=np.sum(a[i:w+i])/w
    print('Y' + str(i+1),round(ans,2))

In [25]:
a=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
movavg(a,4)


 Original array : 
 [ 10  20  30  40  50  60  70  80  90 100]

 Thus, the moving average sequence of above array is : 

Y1 25.0
Y2 35.0
Y3 45.0
Y4 55.0
Y5 65.0
Y6 75.0
Y7 85.0


In [26]:
a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
movavg(a,3)


 Original array : 
 [  3   5   7   2   8  10  11  65  72  81  99 100 150]

 Thus, the moving average sequence of above array is : 

Y1 5.0
Y2 4.67
Y3 5.67
Y4 6.67
Y5 9.67
Y6 28.67
Y7 49.33
Y8 72.67
Y9 84.0
Y10 93.33
Y11 116.33
